idf_component_register(
    SRCS
        "main.cpp"
        "src/solar_sensor.cpp"
        "src/solar_sensor_nvs.cpp"
        "src/ina_sensor_task.cpp"
        "src/command_handler.cpp"
        "src/day_night_controller.cpp"
        "src/ota_controller.cpp"
    INCLUDE_DIRS
        "include"
        "include/interfaces"
        "."
    REQUIRES
        smart-farm-common
        espnow_manager
        wifi_manager
        ota_manager
        time_manager
        battery_monitor
        idf_hals
        power_control
        ina226_driver
)